services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: pipo-processor-db
    ports:
      - "542:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=processor-db
    