services:
  redis:
    image: redis
    container_name: pipo-redis
    ports:
      - 6379:6379
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: pipo-redis-gui
    depends_on:
      - redis
    environment:
      - REDIS_HOSTS=redis:redis
    ports:
      - 8081:8081
  ingestor:
    container_name: pipo-ingestor
    depends_on:
      - redis
    build:
      context: ./apps/ingestor
      dockerfile: Dockerfile
    env_file:
      - ./apps/ingestor/.env
    ports:
      - 3000:3000
  processor:
    container_name: pipo-processor
    depends_on:
      processor-db:
        condition: service_healthy
      redis:
        condition: service_started
    build:
      context: ./apps/processor
      dockerfile: Dockerfile
    env_file:
      - ./apps/processor/.env
    ports:
      - 3001:3001
  processor-db:
    image: bitnami/postgresql:latest
    container_name: pipo-processor-db
    ports:
      - "542:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=processor-db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5
      timeout: 5s
  