apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-broker-stateful-set
spec:
  serviceName: redis-broker-service
  replicas: 1
  selector:
    matchLabels:
      app: redis-broker
  template:
    metadata:
      labels:
        app: redis-broker
    spec:
      containers:
        - name: redis-broker
          image: redis:7.2-alpine
          ports:
            - containerPort: 6379
              name: redis
          args: ["--appendonly", "yes"]
          volumeMounts:
            - name: redis-data
              mountPath: /var/lib/redis/data
  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: standard
        resources:
          requests:
            storage: 1Gi
