- op: replace
  path: /metadata/name
  value: ingestor-api-deployment
- op: replace
  path: /spec/selector/matchLabels/app
  value: ingestor-api
- op: replace
  path: /spec/template/metadata/labels/app
  value: ingestor-api
- op: replace
  path: /spec/template/spec/containers/0/name
  value: ingestor-api
- op: replace
  path: /spec/template/spec/containers/0/ports/0/containerPort
  value: 3000
- op: replace
  path: /spec/template/spec/containers/0/readinessProbe/httpGet/port
  value: 3000
- op: replace
  path: /spec/template/spec/containers/0/livenessProbe/httpGet/port
  value: 3000
- op: add
  path: /spec/template/spec/containers/0/envFrom
  value:
    - configMapRef:
        name: ingestor-api-config
    - secretRef:
        name: ingestor-api-secret
