apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - config-map.yml
  - secret.yml
  - ../../../shared/base/api/deployment

namePrefix: ingestor-

images:
  - name: charmingruby/podummy
    newName: charmingruby/pipoingestor
    newTag: latest

patches:
  - path: deployment-patch.yml
    target:
      kind: Deployment
      name: api-deployment
