apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - service.yml
  - config-map.yml
  - secret.yml
  - ../../../shared/base/api/deployment

images:
  - name: charmingruby/podummy
    newName: charmingruby/pipoingestor
    newTag: latest

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: api-deployment
    path: deployment-patch.yml
