apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingestor-api-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: pipo.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ingestor-api-service
                port:
                  number: 3000
