apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../shared/base/api/deployment

namePrefix: processor-

images:
  - name: charmingruby/podummy
    newName: charmingruby/pipoprocessor
    newTag: latest

patches:
  - path: deployment-patch.yml
    target:
      kind: Deployment
      name: api-deployment
