apiVersion: v1
kind: Secret
metadata:
  name: processor-api-secret
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXM6Ly9hZG1pbjphZG1pbkBwcm9jZXNzb3ItZGF0YWJhc2Utc2VydmljZS5yZWZpbmVyeS5zdmMuY2x1c3Rlci5sb2NhbDo1NDMyL3BpcG8tcHJvY2Vzc29yP3NzbG1vZGU9ZGlzYWJsZQ== # base64 postgres://admin:admin@processor-database-service.refinery.svc.cluster.local:5432/pipo-processor?sslmode=disable
  REDIS_URL: cmVkaXMtYnJva2VyLXN0YXRlZnVsLXNldC0wLnJlZGlzLWJyb2tlci1zZXJ2aWNlLnNoYXJlZC5zdmMuY2x1c3Rlci5sb2NhbDo2Mzc5 # base64 redis-broker-stateful-set-0.redis-broker-service.shared.svc.cluster.local:6379
  SENTIMENT_INGESTED_TOPIC: c2VudGltZW50LmluZ2VzdGVk # base64 sentiment.ingested

