services:
  api:
    build:
      context: ../api
      dockerfile: Dockerfile
    env_file:
      - ../api/.env
    ports:
      - 8080:8080
  redis:
    image: redis
    container_name: pipo-redis
    ports:
      - 6379:6379
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: pipo-redis-gui
    depends_on:
      - redis
    environment:
      - REDIS_HOSTS=redis:redis
    ports:
      - 8081:8081
  