apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: processor-database-stateful-set
spec:
  selector:
    matchLabels:
      app: processor-database
  serviceName: processor-database
  replicas: 2
  template:
    metadata:
      labels:
        app: processor-database
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - name: postgres
              containerPort: 5432
          envFrom:
            - secretRef:
                name: processor-database-secret
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
