name: Build

on:
  push:
    branches:
      - main

jobs:
  load-services:
    uses: ./.github/workflows/load-services.yml

  build:
    needs: load-services
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.load-services.outputs.services) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{vars.GO_VERSION}}

      - name: Build ${{ matrix.service.name }}
        working-directory: ${{ matrix.service.path }}
        run: |
          go build -o ../../bin/${{ matrix.service.name }} ${{ matrix.service.main }}
