name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        service:
          - name: ingestor
            path: apps/ingestor
            main: cmd/ingestor/main.go
          - name: processor
            path: apps/processor
            main: cmd/processor/main.go
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{vars.GO_VERSION}}
          cache: false

      - name: Build ${{ matrix.service.name }}
        working-directory: ${{ matrix.service.path }}
        run: |
          go build -o ../../bin/${{ matrix.service.name }} ${{ matrix.service.main }}