name: Lint

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - name: api
            path: service/api
          - name: worker
            path: service/worker
          - name: lib
            path: lib
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{vars.GO_VERSION}}
          cache: false

      - name: Install dependencies
        working-directory: ${{ matrix.service.path }}
        run: |
          go mod tidy

      - name: Lint
        uses: golangci/golangci-lint-action@v8
        with:
          working-directory: ${{ matrix.service.path }}
          version: v2.1
