name: Lint

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - name: api
            path: service/api
            main: cmd/api/main.go
          - name: worker
            path: service/worker
            main: cmd/worker/main.go
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{vars.GO_VERSION}}
          cache: false

      - name: Install dependencies
        run: |
          go work sync
          cd ${{ matrix.service.path }}
          go mod tidy

      - name: Lint
        uses: golangci/golangci-lint-action@v4
        with:
          working-directory: ${{ matrix.service.path }}
          version: v1.55.2
          args: --timeout=3m --out-format=colored-line-number
