name: Release Images

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        service:
          - name: ingestor
            image: charmingruby/pipoingestor
            dockerfile: apps/ingestor/Dockerfile
            context: apps/ingestor
          - name: processor
            image: charmingruby/pipoprocessor
            dockerfile: apps/processor/Dockerfile
            context: apps/processor
          - name: processor-migrator
            image: charmingruby/pipoprocessormigrator
            dockerfile: apps/processor/Dockerfile.migrate
            context: apps/processor

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Generate tags
      id: generate_tag
      run: |
        SHA=$(echo $GITHUB_SHA | head -c7)
        TAGS="${{ matrix.service.image }}:latest,${{ matrix.service.image }}:${SHA}"
        echo "tags=${TAGS}" >> $GITHUB_OUTPUT
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: ${{ matrix.service.context }}
        file: ${{ matrix.service.dockerfile }}
        push: true
        tags: ${{ steps.generate_tag.outputs.tags }}