name: Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        service:
          - name: ingestor
            path: apps/ingestor
          - name: processor
            path: apps/processor
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{vars.GO_VERSION}}
          cache: false

      - name: Install dependencies
        working-directory: ${{ matrix.service.path }}
        run: |
          go mod tidy

      - name: Test ${{ matrix.service.name }}
        working-directory: ${{ matrix.service.path }}
        run: |
          go test -v ./...